sudo: false
os: linux
language: c
before_install:
  sudo apt-get install libusb-1.0-0-dev

deploy:
  provider: releases
  api_key: "54b344761f9c732a48dff0fa9141c4623ec329ef"
  file: dmrconfig
  skip_cleanup: true
  keep-history: true
  on:
    branch: bin
    tags: true
after_success:
  bash <(curl -s https://codecov.io/bash)
