sudo: false
os: linux
language: c
before_install:
  sudo apt-get install libusb-1.0-0-dev
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: bin
